---
- name: security_policy | Packages
  become: true
  package:
    name: libpam-pwquality

- name: security_policy | Find Home directories
  become: true
  find:
    recurse: false
    file_type: directory
    paths:
      - /home
  register: _home_dirs

- debug:
    var: _home_dirs

- name: security_policy | Home Directory Permissions
  become: true
  file:
    path: "{{ item }}"
    mode: "u=rwx,go="
  loop: "{{ _home_dirs.files | map(attribute='path') | list }}"
  when: _home_dirs is succeeded

- name: security_policy | Execution Restrictions
  include_tasks: security_policy_restrict_binaries.yml
  loop: "{{ ncsc_eud_restricted_execs }}"

- name: security_policy | DConf System Configuration Dir
  become: true
  file:
    path: /etc/dconf/db/local.d/locks
    state: directory
    mode: "u=rwx,go=rx"
    owner: root
    group: root

- name: security_policy | Gnome Screen-Saver Settings
  become: true
  copy:
    dest: /etc/dconf/db/local.d/00_screensaver-lock
    content: |
      {{ ansible_managed | comment }}
      [org/gnome/desktop/session]
      idle-delay={{ ncsc_eud_gnome_screensaver_idle_secs }}
      [org/gnome/desktop/screensaver]
      lock-enabled=1
      lock-delay=0
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify: dconf update

- name: security_policy | Gnome Screen Saver Lock
  become: true
  copy:
    dest: /etc/dconf/db/local.d/locks/00_screensaver-lock
    content: |
      /org/gnome/desktop/session/idle-delay
      /org/gnome/desktop/screensaver/lock-enabled
      /org/gnome/desktop/screensaver/lock-delay
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify: dconf update

- name: security_policy | DConf User Profile
  become: true
  copy:
    dest: /etc/dconf/profile/user
    content:
      user-db:user
      system-db:local
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify: dconf update

- name: security_policy | Enable SSH through Firewall
  become: true
  command: /usr/sbin/ufw allow OpenSSH
  tags:
    - skip_ansible_lint

- name: security_policy | Enable firewall
  become: true
  command: /usr/sbin/ufw --force enable
  tags:
    - skip_ansible_lint
