---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
platforms:
  - name: "ubuntu1804"
    box: "peru/ubuntu-18.04-desktop-amd64"
    cpus: 2
    memory: 2048
provisioner:
  name: ansible
  config_options:
    defaults:
      fact_caching: jsonfile
      fact_caching_connection: $MOLECULE_EPHEMERAL_DIRECTORY/.facts
      fact_caching_timeout: 600
      gather_timeout: 20
  inventory:
    host_vars:
      ubuntu1804:
        ansible_python_interpreter: /usr/bin/python3
        ansible_managed: "Managed by Ansible"
  lint:
    name: ansible-lint
verifier:
  name: goss
  lint:
    name: yamllint
